#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Redis
  session:
    store-type: redis

  #OAuth2
  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: gXIHs8uepXwClgDlEclE
            client-secret: TZXCWxiqmj
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,ncikname,email,mobile

          #kakao
          kakao:
            client-id: 43642f09d4a5198b6604fe087e1e9b6c
            client-secret: veRDVt2NVsnvEzWFMuTz4sXTP7QI61Xf
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client_name: kakao

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

